/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminQRSettings {
  'autoQrAmount' : bigint,
  'permanentQrKey' : string,
}
export interface PaymentConfirmation {
  'orderId' : bigint,
  'timestamp' : bigint,
  'confirmedByAdmin' : boolean,
}
export interface ServiceOrder {
  'status' : string,
  'serviceName' : string,
  'documentKey' : string,
  'name' : string,
  'orderId' : bigint,
  'address' : string,
  'timestamp' : bigint,
  'customerId' : string,
  'mobile' : string,
  'amount' : bigint,
}
export interface UserProfile { 'name' : string, 'mobile' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Admin-only: confirm that a payment has been received for an order,
   * / and advance the order status to 'Payment Completed'.
   */
  'confirmPayment' : ActorMethod<[bigint], undefined>,
  /**
   * / Admin-only: retrieve all submitted orders.
   */
  'getAllOrders' : ActorMethod<[], Array<ServiceOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Any caller may query orders for a given customerId.
   * / The customerId acts as the app-level authorization token.
   * / Admins (IC-level) may also query any customer's orders.
   */
  'getOrdersByCustomer' : ActorMethod<[string], Array<ServiceOrder>>,
  /**
   * / Any caller may check the payment confirmation for an order.
   * / The customerId in the order acts as the app-level authorization token.
   */
  'getPaymentConfirmation' : ActorMethod<[bigint], [] | [PaymentConfirmation]>,
  /**
   * / Anyone may retrieve the permanent QR image (needed to display payment QR to customers).
   */
  'getPermQR' : ActorMethod<[], string>,
  /**
   * / Anyone may retrieve the full QR settings (amount needed for auto-QR generation).
   */
  'getQRSettings' : ActorMethod<[], AdminQRSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Anyone (including guests) may attempt to log in.
   */
  'loginCustomer' : ActorMethod<[string, string], boolean>,
  /**
   * / Anyone (including guests) may register a new customer account.
   */
  'registerCustomer' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Admin-only: set the permanent QR image and/or auto-QR amount.
   */
  'setPermQR' : ActorMethod<[string, bigint], undefined>,
  /**
   * / The application uses a mobile/password authentication system independent of
   * / Internet Identity. Customers are identified by their customerId (mobile number).
   * / No IC-level role check is applied here; the customerId passed by the frontend
   * / represents the logged-in customer's identity within the app's own auth system.
   */
  'submitOrder' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    bigint
  >,
  /**
   * / Admin-only: update the status of a service order.
   */
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];